{{- $components := list "moni-agent" -}}
{{- range $name := $components }}
{{- $config := index $.Values $name -}}
{{- if and $config $config.enabled }}
---
{{ include "deploy-bot.deployment" (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "name" $name "config" $config) }}
{{- end }}
{{- end }}
