apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.backend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.backend.podLabels.app }}
