apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.frontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.podLabels.app }}
