name: Security Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend-security-check:
    name: Backend security check
    environment: ENV
    runs-on: ubuntu-latest
    needs: backend-install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm

      - name: Install backend dependencies
        run: npm ci

      - name: Run security check
        run: npm audit --audit-level=low 
        

  frontend-lint-and-build:
    name: Frontend lint and build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Lint frontend
        run: npm run lint

      - name: Build frontend
        run: npm run build
