name: Moni Agent - $(Build.BuildId)

trigger: none

resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: DevOps/Pipeline_Templates
      ref: refs/heads/pipeline-mt5-checker

extends:
  template: pipeline.moni-agent.yaml@pipeline-templates
  parameters:
    ServiceName: 'moni-agent'
    ImageName: 'moni-agent'
    VariableGroupNamePrefix: 'MoniAgent-<env>'
    ServiceConnection: 'LFGLOBALTECH-CONTRIBUTOR-PORTAL-Administrator'
    DockerfilePath: 'Dockerfile'
    DockerfileContext: '.'
    ServicePath: '.'
    isDeployAks: true
    isDeployAppService: false
    isBuildStage: true
